apiVersion: 1

datasources:
  - name: Neon Postgres
    type: postgres
    access: proxy
    isDefault: true

    url: ep-xxxx.neon.tech:5432
    user: neondb_owner

    secureJsonData:
      password: ${NEON_DB_PASSWORD}

    jsonData:
      database: neondb       # ğŸ‘ˆ à¸ªà¸³à¸„à¸±à¸à¸¡à¸²à¸
      sslmode: require
      postgresVersion: 1400
